USING Simatic.Ax.Mp;

NAMESPACE SimaticAxMp
    
    {TestFixture}
    CLASS Test_SensorInfeed
        {Test}
        METHOD PUBLIC Test_x
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
        {Test}
        METHOD PUBLIC Test_y
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
    END_CLASS
    
    {TestFixture}
    CLASS Test_SensorWork
        {Test}
        METHOD PUBLIC Test_x
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
        {Test}
        METHOD PUBLIC Test_y
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
    END_CLASS
    
    {TestFixture}
    CLASS Test_SensorOutfeed
        {Test}
        METHOD PUBLIC Test_x
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
        {Test}
        METHOD PUBLIC Test_y
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
    END_CLASS
    
    {TestFixture}
    CLASS Test_AxisControl
        {Test}
        METHOD PUBLIC Test_x
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
        {Test}
        METHOD PUBLIC Test_y
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
    END_CLASS
    
    {TestFixture}
    CLASS Test_ConveyorBelt
        {Test}
        METHOD PUBLIC Test_Init
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
        {Test}
        METHOD PUBLIC Test_MoveToSensor_Work_dir1
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
        {Test}
        METHOD PUBLIC Test_MoveToSensor_Work_dir0
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
        {Test}
        METHOD PUBLIC Test_MoveToSensor_Outfeed_dir1
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
        {Test}
        METHOD PUBLIC Test_MoveToSensor_Outfeed_dir0
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
        METHOD PUBLIC Test_MoveToSensor_Infeed_dir1
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD
        {Test}
        METHOD PUBLIC Test_MoveToSensor_Infeed_dir0
            ; // AxUnit.Assert.Equal(expected := y, actual := x);
        END_METHOD

    END_CLASS

END_NAMESPACE